import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Providers from './providers'
// import ThemeToogle from '@/components/Utilities/ThemeToogle'

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata = {
  title: 'Ainime List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-color-primary dark:bg-color-dark`} >
        <Providers>
          {/* <ThemeToogle /> */}
          <Navbar />
          {children}
        </Providers>
      </body>
    </html >
  )
}
